### ISSUE TITLE
2015-12-06 22:26:28 最新的代码 exec模块缺少import cache包

### ISSUE THREAD

**Issue by wwek** [andeya/pholcus#7]
缺少本包,需要增加
    "github.com/henrylee2cn/pholcus/runtime/cache"

[root@dev henrylee2cn]# go get -u  github.com/henrylee2cn/pholcus
# github.com/henrylee2cn/pholcus/exec

pholcus/exec/exec_linux.go:18: undefined: cache in cache.Task

**Comment by andeya** [comment]
感谢你的指正，已修复

**Comment by wwek** [comment]
最新代码无论是 默认demo osx 还是linux  浏览器访问都会出现这样. 浏览器页面也打不开

```
➜  appgopa git:(master) ✗ ./appgopa
2015/12/07 21:27:02 [pholcus] server Running on 0.0.0.0:9090
2015/12/07 21:27:08 http: panic serving 127.0.0.1:51328: runtime error: invalid memory address or nil pointer dereference
goroutine 93 [running]:
net/http.(*conn).serve.func1(0xc8201322c0, 0x1566da0, 0xc820086160)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
text/template.errRecover(0xc82004fa08)
    /usr/local/go/src/text/template/exec.go:100 +0xbb
text/template.(*Template).Execute(0x0, 0x1567020, 0xc820132370, 0x517c60, 0xc820194210, 0x0, 0x0)
    /usr/local/go/src/text/template/exec.go:140 +0x235
github.com/henrylee2cn/pholcus/web.web(0x1566f20, 0xc820132370, 0xc8200ea1c0)
    /Users/wwek/Projects/GoProjects/src/github.com/henrylee2cn/pholcus/web/httpController.go:54 +0xb47
net/http.HandlerFunc.ServeHTTP(0x834240, 0x1566f20, 0xc820132370, 0xc8200ea1c0)
    /usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820076de0, 0x1566f20, 0xc820132370, 0xc8200ea1c0)
    /usr/local/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc8201a8fc0, 0x1566f20, 0xc820132370, 0xc8200ea1c0)
    /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8201322c0)
    /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6
2015/12/07 21:27:08 http: panic serving 127.0.0.1:51329: runtime error: invalid memory address or nil pointer dereference
goroutine 4 [running]:
net/http.(*conn).serve.func1(0xc8205dc000, 0x1566da0, 0xc8205da000)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
```
